### ISSUE TITLE
Custom component not working for me

### ISSUE THREAD

**Issue by platte-73** [robertklep/esphome-custom-component#1]
I have tried this to get my custom_components working again. It will compile but my custom components do not work. 

This is what I had before in custom_components

custom_component:
- lambda: |-
    auto myComponent = new veranda(id(led_starten), id(led_stoppen), id(sidebars), id(rgb_r), id(rgb_g), id(rgb_b));
    App.register_component(myComponent);    
    return {myComponent};

**Comment by robertklep** [comment]
Can you share your full YAML file, including the implementation of the `veranda` component?

If it compiles, the custom component implementation has worked, and perhaps there's something else that has changed that is causing your issues.

**Comment by platte-73** [comment]
This is my veranda.h file
```
#include <esphome.h>
#include <Adafruit_NeoPixel.h>

#define PIN D3
#define NUM_LEDS 300

Adafruit_NeoPixel strip = Adafruit_NeoPixel(NUM_LEDS, PIN, NEO_GRB + NEO_KHZ800);
int sidebar1;
int sidebar2;
int horbar;
class veranda : public Component
{
  public:
    unsigned long last_led_change;
    bool starten = false;
    bool stoppen = false;
    bool sidebars = false;
    int led_r = 50;
    int led_g = 0;
    int led_b = 50;


    veranda(esphome::template_::TemplateSwitch *&_starten, esphome::template_::TemplateSwitch *&_stoppen, esphome::template_::TemplateSwitch *&_sidebars, esphome::template_::TemplateNumber *&_led_r, esphome::template_::TemplateNumber *&_led_g, esphome::template_::TemplateNumber *&_led_b)
    {

      _starten->add_on_state_callback([this](bool newState)
      {
        starten = newState;
      });
      _stoppen->add_on_state_callback([this](bool newState)
      {
        stoppen = newState;
      });
      _sidebars->add_on_state_callback([this](bool newState)
      {
        sidebars = newState;
      });
      _led_r->add_on_state_callback([this](float led_r_n)
      {
        led_r = led_r_n;
      });
      _led_g->add_on_state_callback([this](float led_g_n)
      {
        led_g = led_g_n;
      });
      _led_b->add_on_state_callback([this](float led_b_n)
      {
        led_b = led_b_n;
      });
    }

    void setup() override
    {
      strip.begin();
      strip.show(); // Initialize all pixels to 'off'
    }

    void loop() override
    {
      if (sidebars == false) {
        sidebar1 = 84;
        sidebar2 = 84;
        horbar = 132;
        setBars(0, 0, 0 , 2);
      } else {
        sidebar1 = 0;
        sidebar2 = 0;
      }
      if (starten == true && id(veranda_neopixel) == false) {
        id(led_stoppen).publish_state(false);
       // OutsideToCenter(led_r, led_g, led_b, 6, 4, 50);
        CylonBounce(led_r, led_g, led_b, 6, 2, 50);
        starten = false;
    
      } else {
        if (stoppen == true && id(veranda_neopixel) == false) {
          id(led_starten).publish_state(false);
          colourWipeEnd(strip.Color((led_r / 2), (led_g / 2), (led_b / 2)), 2);
          colourWipeStart(strip.Color(0, 0, 0), 2);
          setAll(0, 0, 0);
          stoppen = false;
          
        } else {
          return;
        }
      }
      strip.show();
    }

    void colourWipeStart(uint32_t c, uint16_t wait) {
      for (uint16_t j = 0; j < NUM_LEDS / 2; j++) {
        strip.setPixelColor(j, c);
        strip.setPixelColor(NUM_LEDS - j, c);
        strip.show();
        delay(wait);
      }
    }

    void colourWipeEnd(uint32_t c, uint16_t wait) {
      for (uint16_t j = NUM_LEDS / 2; j < NUM_LEDS; j++) {
        strip.setPixelColor(j, c);
        strip.setPixelColor(NUM_LEDS - j - 1, c);
        strip.show();
        delay(wait);
      }
    }


    void setAll(byte red, byte green, byte blue) {
      for (int i = 0; i < NUM_LEDS; i++ ) {
        strip.setPixelColor(i, red, green, blue);
      }
      strip.show();
    }

    void setBars(byte red, byte green, byte blue, uint16_t wait) {
      for (int i = 0; i < sidebar1; i++ ) {
        strip.setPixelColor(i, red, green, blue);
        strip.setPixelColor((horbar + sidebar2 + i), red, green, blue);
        strip.show();
        delay(wait);
      }
    }


void CylonBounce(byte red, byte green, byte blue, int EyeSize, int SpeedDelay, int ReturnDelay){
  for(int i = 0; i < (NUM_LEDS/2)-EyeSize-2; i++) {
    strip.setPixelColor(i, red/10, green/10, blue/10);
    strip.setPixelColor(NUM_LEDS -i, red/10, green/10, blue/10);
    for(int j = 1; j <= EyeSize; j++) {
      strip.setPixelColor(i+j, red, green, blue);
      strip.setPixelColor(NUM_LEDS-i+j, red, green, blue);
    }
    strip.setPixelColor(i+EyeSize+1, red/10, green/10, blue/10);
    strip.setPixelColor(NUM_LEDS-i+EyeSize+1, red/10, green/10, blue/10);
    strip.show();
    delay(SpeedDelay);
  }
   for(int i = (NUM_LEDS/2)-EyeSize-2; i < NUM_LEDS; i++) {
    strip.setPixelColor(i, red, green, blue);
    strip.setPixelColor(NUM_LEDS -i, red, green, blue);
    for(int j = 1; j <= EyeSize; j++) {
      strip.setPixelColor(i+j, red*2, green*2, blue*2);
      strip.setPixelColor(NUM_LEDS-i+j, red*2, green*2, blue*2);
    }
    strip.setPixelColor(i+EyeSize+1, red, green, blue);
    strip.setPixelColor(NUM_LEDS-i+EyeSize+1, red, green, blue);
    strip.show();
    delay(SpeedDelay);
  }
} 

void CylonBounce1(byte red, byte green, byte blue, int EyeSize, int SpeedDelay, int ReturnDelay){
  for(int i = 0; i < (NUM_LEDS); i++) {
    strip.setPixelColor(i, red/10, green/10, blue/10);
    strip.setPixelColor(NUM_LEDS -i, red/10, green/10, blue/10);
    if (i > 150) {
      strip.setPixelColor(i, red, green, blue);
      strip.setPixelColor(NUM_LEDS -i, red, green, blue);
    }
    
    strip.show();
    
    delay(SpeedDelay);
  }
  }


void CylonBounceRet(byte red, byte green, byte blue, int EyeSize, int SpeedDelay, int ReturnDelay){
  for(int i = (NUM_LEDS/2)-EyeSize-2; i < NUM_LEDS; i++) {
    strip.setPixelColor(i, red, green, blue);
    strip.setPixelColor(NUM_LEDS -i, red, green, blue);
    for(int j = 1; j <= EyeSize; j++) {
      strip.setPixelColor(i+j, red*2, green*2, blue*2);
      strip.setPixelColor(NUM_LEDS-i+j, red*2, green*2, blue*2);
    }
    strip.setPixelColor(i+EyeSize+1, red, green, blue);
    strip.setPixelColor(NUM_LEDS-i+EyeSize+1, red, green, blue);
    strip.show();
    delay(SpeedDelay);
  }
}
void OutsideToCenter(byte red, byte green, byte blue, int EyeSize, int SpeedDelay, int ReturnDelay) {
  for(int i = 0; i<=((NUM_LEDS-EyeSize)/2); i++) {
    setAll(0,0,0);
   
    strip.setPixelColor(i, red/10, green/10, blue/10);
    for(int j = 1; j <= EyeSize; j++) {
      strip.setPixelColor(i+j, red, green, blue);
    }
    strip.setPixelColor(i+EyeSize+1, red/10, green/10, blue/10);
   
    strip.setPixelColor(NUM_LEDS-i, red/10, green/10, blue/10);
    for(int j = 1; j <= EyeSize; j++) {
      strip.setPixelColor(NUM_LEDS-i-j, red, green, blue);
    }
    strip.setPixelColor(NUM_LEDS-i-EyeSize-1, red/10, green/10, blue/10);
   
    strip.show();
    delay(SpeedDelay);
  }
  delay(ReturnDelay);
}
void meteorRain(byte red, byte green, byte blue, byte meteorSize, byte meteorTrailDecay, boolean meteorRandomDecay, int SpeedDelay) {  
 
  for(int i = 0; i < NUM_LEDS+NUM_LEDS; i++) {
   
   
    // fade brightness all LEDs one step
    for(int j=0; j<NUM_LEDS; j++) {
      if( (!meteorRandomDecay) || (random(10)>5) ) {
        fadeToBlack(j, meteorTrailDecay );        
      }
    }
   
    // draw meteor
    for(int j = 0; j < meteorSize; j++) {
      if( ( i-j <NUM_LEDS) && (i-j>=0) ) {
        strip.setPixelColor(i-j, red, green, blue);
      }
    }
   
    strip.show();
    delay(SpeedDelay);
  }
}

void fadeToBlack(int ledNo, byte fadeValue) {
 #ifdef ADAFRUIT_NEOPIXEL_H
    // NeoPixel
    uint32_t oldColor;
    uint8_t r, g, b;
    int value;
   
    oldColor = strip.getPixelColor(ledNo);
    r = (oldColor & 0x00ff0000UL) >> 16;
    g = (oldColor & 0x0000ff00UL) >> 8;
    b = (oldColor & 0x000000ffUL);

    r=(r<=10)? 0 : (int) r-(r*fadeValue/256);
    g=(g<=10)? 0 : (int) g-(g*fadeValue/256);
    b=(b<=10)? 0 : (int) b-(b*fadeValue/256);
   
    strip.setPixelColor(ledNo, r,g,b);
 #endif
 #ifndef ADAFRUIT_NEOPIXEL_H
   // FastLED
   leds[ledNo].fadeToBlackBy( fadeValue );
 #endif  
}

};
`
```

**Comment by platte-73** [comment]
This is my old yaml file who worked before they removed the custom component
```
substitutions:
  name: Veranda ledstrip
  vdate: "2024.05.1" 
  date: "01-May-2024"
  author: "Pietje puk"
  device_description: ${name} made by ${author} ${vdate}
  board: "Wemos D1 mini"
  num_leds: "300"

esphome:
  name: veranda-ledstrip
  comment: '${device_description}'
  friendly_name: veranda ledstrip
  project:
    name: Pietje Puk.${name}
    version: "D1 mini"
  platform: ESP8266
  board: d1_mini
  includes:
    - "veranda.h"

  libraries:
    - adafruit/Adafruit NeoPixel @ ^1.10.6
# Enable logging
logger:
  level: DEBUG
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "0Dxvh4t8MYNdQbwxqoKG9ub0ovpSjLs5V/omxBE/Kzw="

ota:
 platform: esphome
 password: "c2133f61e62efed0eb768c1fe197b064"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret static_ip_veranda
    gateway: !secret gateway
    subnet: !secret subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Veranda Fallback Hotspot"
    password: "Ofpm6BOxhqJB"

captive_portal:

sensor:
  # Extra sensor to keep an eye on the Wi-Fi signal
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s  

  - platform: uptime
    name: Uptime
    id: uptime_s
    update_interval: 10s

text_sensor:     
  - platform: template
    name: "Software"
    id: veranda_software
    icon: 'mdi:alpha-v-box-outline' 
    update_interval: 12h
    lambda: |-
      return {"${vdate}"};

  - platform: template
    name: "Hardware"
    id: veranda_hardware
    icon: 'mdi:card-outline' 
    update_interval: 12h
    lambda: |-
      return {"${board}"};

switch:
  - platform: template
    name: "Starten"
    id: led_starten
    optimistic: True
    restore_mode: ALWAYS_OFF

  - platform: template
    name: "Stoppen"
    id: led_stoppen
    optimistic: True
    restore_mode: ALWAYS_OFF
  - platform: template

    name: "Side Bars"
    id: sidebars
    optimistic: True
    restore_mode: ALWAYS_ON

# set the color of the leds with RGB Value. 1st Red 2nd Green 3d Blue standard value R=239 G=235 B=216
number:
  - platform: template
    name: "1.Red"
    id: rgb_r
    optimistic: true
    mode: auto
    initial_value: 50
    min_value: 0
    max_value: 255
    step: 1

  - platform: template
    name: "2.Green"
    id: rgb_g
    optimistic: true
    mode: auto
    initial_value: 0
    min_value: 0
    max_value: 255
    step: 1

  - platform: template
    name: "3.Blue"
    id: rgb_b
    optimistic: true
    mode: auto
    initial_value: 50
    min_value: 0
    max_value: 255
    step: 1 

globals:
  - id: veranda_neopixel
    type: bool

light:
  - platform: neopixelbus
    id: light_effect
    type: GRB
    variant: WS2812
    pin: D3
    num_leds: "${num_leds}"
    name: "veranda(color Wheel)"
    icon: mdi:led-strip-variant
    on_turn_on:
      then: 
        - light.turn_on:
            id: light_effect
            brightness: 50%
            red: 100%
            green: 0%
            blue: 100% 
        - lambda: |-
              id(veranda_neopixel) = true;
    on_turn_off:
      then:
        - lambda: |-
              id(veranda_neopixel) = false;

    effects:
      - !include esphome_led_effects/effects/fire.yaml
      - !include esphome_led_effects/effects/bluez.yaml
      - !include esphome_led_effects/effects/candy_cane.yaml
      - !include esphome_led_effects/effects/christmas.yaml
      - !include esphome_led_effects/effects/flames.yaml
      - !include esphome_led_effects/effects/lightning.yaml
      - !include esphome_led_effects/effects/policeall.yaml
      - !include esphome_led_effects/effects/vesuvius.yaml
      - !include esphome_led_effects/effects/wheel_of_color.yaml
      - !include esphome_led_effects/effects/wipe_in.yaml
      - !include esphome_led_effects/effects/wipe_out.yaml
      - addressable_rainbow:
          name: "Rainbow Spinner"
          speed: 8
          width: "${num_leds}"
   
                
custom_component:
- lambda: |-
    auto myComponent = new veranda(id(led_starten), id(led_stoppen), id(sidebars), id(rgb_r), id(rgb_g), id(rgb_b));
    App.register_component(myComponent);    
    return {myComponent};
```

**Comment by robertklep** [comment]
Can you also provide the YAML file that you're using now?

**Comment by platte-73** [comment]
The only thing I have changed is the board info because they removed the platform also. But I'm not at home at the moment so I cant provide you the new yaml. But I only changed this in my yaml

This I have replaced
```
custom_component:
- lambda: |-
    auto myComponent = new veranda(id(led_starten), id(led_stoppen), id(sidebars), id(rgb_r), id(rgb_g), id(rgb_b));
    App.register_component(myComponent);    
    return {myComponent};
```

With this
```
external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]
```

**Comment by robertklep** [comment]
@platte-73 literally the only thing you need to do is add the `external_components` block 😄  the `custom_component` should still be there.

**Comment by platte-73** [comment]
Yes it is working. I really thought I had to replace the custom component lines

**Comment by platte-73** [comment]
With the new ESP-Home build they changed something with the register_component

custom_component:
- lambda: |-
    auto myComponent = new veranda(id(led_starten), id(led_stoppen), id(sidebars), id(rgb_r), id(rgb_g), id(rgb_b));
    App.register_component(myComponent);    
    return {myComponent};

now App.register_component(myComponent)
should be App.register_component_(myComponent)

But something in the .h file also need to be changed. I have this 

class veranda : public Component
{
  public:
    unsigned long last_led_change;
    bool starten = false;
    bool stoppen = false;
    bool sidebars = false;
    int led_r = 50;
    int led_g = 0;
    int led_b = 50;


    veranda(esphome::template_::TemplateSwitch *&_starten, esphome::template_::TemplateSwitch *&_stoppen, esphome::template_::TemplateSwitch *&_sidebars, esphome::template_::TemplateNumber *&_led_r, esphome::template_::TemplateNumber *&_led_g, esphome::template_::TemplateNumber *&_led_b)
    {

      _starten->add_on_state_callback([this](bool newState)
      {
        starten = newState;
      });
      _stoppen->add_on_state_callback([this](bool newState)
      {
        stoppen = newState;
      });
      _sidebars->add_on_state_callback([this](bool newState)
      {
        sidebars = newState;
      });
      _led_r->add_on_state_callback([this](float led_r_n)
      {
        led_r = led_r_n;
      });
      _led_g->add_on_state_callback([this](float led_g_n)
      {
        led_g = led_g_n;
      });
      _led_b->add_on_state_callback([this](float led_b_n)
      {
        led_b = led_b_n;
      });
    }

Cant figure it out what to change

**Comment by robertklep** [comment]
@platte-73 what error are you getting?

**Comment by platte-73** [comment]
Getting this error

In file included from src/esphome.h:25,
                 from src/main.cpp:3:
src/esphome/components/custom_component/custom_component.h: In constructor 'esphome::custom_component::CustomComponentConstructor::CustomComponentConstructor(const std::function<std::vector<esphome::Component*, std::allocator<esphome::Component*> >()>&)':
src/esphome/components/custom_component/custom_component.h:17:11: error: 'class esphome::Application' has no member named 'register_component'; did you mean 'register_component_'?
   17 |       App.register_component(comp);
      |           ^~~~~~~~~~~~~~~~~~
      |           register_component_

**Comment by robertklep** [comment]
@platte-73 but that one was fixed by adding an underscore, right? You said that "something in the .h file also need to be changed". What led you to that conclusion?

**Comment by platte-73** [comment]
The underscore in the .Yaml file is fixed. But he is still complaining about something else

Because of this

src/esphome/components/custom_component/custom_component.h: In constructor 'esphome::custom_component::CustomComponentConstructor::CustomComponentConstructor(const

I thought this error is for the .h file

**Comment by platte-73** [comment]
Now I see. Its in de custom_componet.h I think. I changed it also there but still an error

#pragma once

#include "esphome/core/component.h"
#include "esphome/core/application.h"

#include <vector>

namespace esphome {
namespace custom_component {

class CustomComponentConstructor {
 public:
  CustomComponentConstructor(const std::function<std::vector<Component *>()> &init) {
    this->components_ = init();

    for (auto *comp : this->components_) {
      App.register_component_(comp);
    }
  }

  Component *get_component(int i) const { return this->components_[i]; }

 protected:
  std::vector<Component *> components_;
};

}  // namespace custom_component
}  // namespace esphome


but still error

In file included from src/esphome.h:25,
                 from src/main.cpp:3:
src/esphome/components/custom_component/custom_component.h: In constructor 'esphome::custom_component::CustomComponentConstructor::CustomComponentConstructor(const std::function<std::vector<esphome::Component*, std::allocator<esphome::Component*> >()>&)':
src/esphome/components/custom_component/custom_component.h:17:35: error: 'void esphome::Application::register_component_(T*) [with T = esphome::Component]' is protected within this context
   17 |       App.register_component_(comp);
      |                                   ^
In file included from src/esphome/components/api/api_frame_helper.h:13,
                 from src/esphome/components/api/api_connection.h:5,
                 from src/esphome.h:4,
                 from src/main.cpp:3:
src/esphome/core/application.h:592:29: note: declared protected here
  592 |   template<typename T> void register_component_(T *comp) {

**Comment by robertklep** [comment]
Ah okay, that means you can't use `App.register_component_` either.

**Comment by pksoft585** [comment]
Github Copilot prepare functional solution for me:

`__init__.py`

```
import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.const import CONF_COMPONENTS, CONF_ID, CONF_LAMBDA

custom_component_ns = cg.esphome_ns.namespace("custom_component")
CustomComponentConstructor = custom_component_ns.class_("CustomComponentConstructor")

MULTI_CONF = True
CONFIG_SCHEMA = cv.Schema(
    {
        cv.GenerateID(): cv.declare_id(CustomComponentConstructor),
        cv.Required(CONF_LAMBDA): cv.returning_lambda,
        cv.Optional(CONF_COMPONENTS): cv.ensure_list(
            cv.Schema({cv.GenerateID(): cv.declare_id(cg.Component)}).extend(
                cv.COMPONENT_SCHEMA
            )
        ),
    }
).extend(cv.COMPONENT_SCHEMA)


async def to_code(config):
    template_ = await cg.process_lambda(
        config[CONF_LAMBDA], [], return_type=cg.std_vector.template(cg.ComponentPtr)
    )

    var = cg.new_Pvariable(config[CONF_ID], template_)
    
    for i, conf in enumerate(config.get(CONF_COMPONENTS, [])):
        comp_ptr = cg.RawExpression(f"({var})->get_component({i})")
        comp = cg.Pvariable(conf[CONF_ID], comp_ptr, cg.Component)
        await cg.register_component(comp, conf)

```

`custom_component.h`

```
#pragma once

#include "esphome/core/component.h"
#include "esphome/core/application.h"

#include <vector>

namespace esphome {
namespace custom_component {

class CustomComponentConstructor {
 public:
  CustomComponentConstructor(const std::function<std::vector<Component *>()> &init) {
    this->components_ = init();
  }

  Component *get_component(int i) const { return this->components_[i]; }

 protected:
  std::vector<Component *> components_;
};

}  // namespace custom_component
}  // namespace esphome

```

Sorry, but I can't make it better...
Maybe it can help.

**Comment by robertklep** [comment]
@pksoft585 interesting, I'll check tomorrow to see if that can be used to fix the issue.

**Comment by robertklep** [comment]
@pksoft585 does this actually work for you? I don't see any calls to a custom component `setup()` or `update()` methods, which (I assume) are only called once the component has been registered (which isn't possible anymore).

**Comment by pksoft585** [comment]
Strange, I can't find yesterday's chat in Copilot here on GitHub. But if I remember correctly, the point was that component registration has to be done in Python in `__init__.py` . I think it's the last line in this code:

_await cg.register_component(comp, conf)_

But I'm really not sure, and I couldn't find the chat. However, this works for me exactly the same as before. The only difference is that I put the modified files in my local folder in esphome, and the rest links to GitHub.

```
external_components:
  - source:
      type: local
      path: my_components
    components: [ custom_component ]
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom ]

```
