### ISSUE TITLE
Need help with  your workaround

### ISSUE THREAD

**Issue by duceduc** [robertklep/esphome-custom-component#3]
I am going through my esphome devices and updating what need to be updated. Long over due. I came across this device that used custom component which still works before esphome pull the plug on it. Looking at your example, I am not sure how to adapt the code into yours. Can you assist? Thank you.

    external_components:
      - source:
          type: git
          url: https://github.com/robertklep/esphome-custom-component
        components: [ custom, custom_component ]

My old working code. I know I need to use the correct platform component as well.

    esphome:
      name: $name
      platform: esp8266
      board: d1_mini
      includes:
        - /config/esphome/components/ld2410_uart.h
      on_boot:
        priority: 600
        # ...
        then:
          - lambda: |-
              auto uart_component = static_cast<LD2410 *>(ld2410);
              uart_component->setNumbers(maxMovingDistanceRange, maxStillDistanceRange, noneDuration);

**Comment by robertklep** [comment]
You literally only have to add that `external_components` block to your existing YAML file 😊

**Comment by duceduc** [comment]
Hello. Is this correct? It validates, but I wanted to confirm before I update.

    external_components: # fix for removal of custom component in esphome 2025.xx and up
      - source:
          type: git
          url: https://github.com/robertklep/esphome-custom-component
        components: [ custom, custom_component ]

    esphome:
      name: $name
      includes:
        - /config/esphome/components/ld2410_uart.h
      on_boot:
        priority: 600
        # ...
        then:
          - lambda: |-
              auto uart_component = static_cast<LD2410 *>(ld2410);
              uart_component->setNumbers(maxMovingDistanceRange, maxStillDistanceRange, noneDuration);
    esp8266:
      board: d1_mini

**Comment by robertklep** [comment]
That's correct (assuming that you also have the rest of the YAML that's required for the LD2410 component).

**Comment by little-chef** [comment]
FYI: There is no need for a seperate git project to get this done. custom_component can be brought back like this:

```
# custom_component has been removed from 2025.2.0 onwards from the esphome
# codebase. As short-term containment the latest known good custom_component from
# ESPHome's last working release in GitHub can be used.
# Just add this to the top-level YAML file of your project.
external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: refs/tags/2024.12.4
    components: [ custom_component ]
```

**Comment by brinzlee** [comment]
ESPHOME Ver 2025.7.1
HomeAssistant Ver  2025.7.2

I'm getting this error but not sure how to address it. Do you have any idea

` WARNING Using `cover.COVER_SCHEMA` is deprecated and will be removed in ESPHome 2025.11.0. Please use `cover.cover_schema(...)` instead. If you are seeing this, report an issue to the external_component author and ask them to update it. https://developers.esphome.io/blog/2025/05/14/_schema-deprecations/. Component using this schema: cover
`
When I try and complie the esphome curtain firmware it is halting and returning this error too

```
 src/curtain.h: In member function 'virtual void CustomAPI::setup()':
 src/curtain.h:145:3: error: 'register_service' was not declared in this scope
   145 |   register_service(&CustomAPI::setMotorNormal, "set_motor_normal");
       |   ^~~~~~~~~~~~~~~~
 Compiling .pioenvs/zemismart-curtain/lib67b/ESP8266WiFi/WiFiUdp.cpp.o
 *** [.pioenvs/zemismart-curtain/src/main.cpp.o] Error 1
```

**Comment by robertklep** [comment]
A warning is just a warning, not an error 😊 

I don't know what the issue with `register_service` is, it could also have been deprecated. Without the rest of the component code I can't help with that.

**Comment by brinzlee** [comment]
Thank you for your kind help...I know this won't be your domain but this is the code I think the issue is with

```
#include "esphome.h"

// basic commands
#define TUYA_OPEN   "55aa000600056604000100"
#define TUYA_CLOSE  "55aa000600056604000101"
#define TUYA_STOP   "55aa000600056604000102"

// set position percentage
#define TUYA_SET_POSITION  "55aa0006000865020004000000" // and 1 byte (0x00-0x64)

// enable/disable reversed motor direction
#define TUYA_DISABLE_REVERSING  "55aa000600056700000100"
#define TUYA_ENABLE_REVERSING  "55aa000600056700000101"

class CustomCurtain : public Component, public Cover {
public:
	CoverTraits get_traits() override {
		auto traits = CoverTraits();
		traits.set_is_assumed_state(false);
		traits.set_supports_position(true);
		traits.set_supports_tilt(false);
		return traits;
	}

	void setup() override {
		position = 1 - id(cover_position);
		publish_state();
	}

	void loop() override {
		while (Serial.available()) {
			readByte(Serial.read());
		}
	}

	void control(const CoverCall &call) override {
		if (call.get_stop()) {
			crc = 0;
			writeHex(TUYA_STOP);
			writeByte(crc);
		}
		if (call.get_position().has_value()) {
			crc = 0;
			uint8_t pos = 100 - (*call.get_position() * 100.0f);
			if (pos == 100) {
				writeHex(TUYA_OPEN);
			} else if (pos == 0) {
				writeHex(TUYA_CLOSE);
			} else {
				writeHex(TUYA_SET_POSITION);
				writeByte(100 - pos);
			}
			writeByte(crc);
		}
	}

	void readByte(uint8_t data) {
		if ((offset == 0 && data == 0x55) || (offset == 1 && data == 0xAA) || offset) {
			buffer[offset++] = data;
			if (offset > 6) {
				int len = buffer[4] << 8 | buffer[5];
				if (7 + len == offset) {
					uint8_t crc = buffer[offset - 1];
					uint8_t sum = 0;
					for (int i = 0; i < offset - 1; i++) sum += buffer[i];
					if (sum == crc) {
						uint8_t cmd_type = buffer[3];
						uint8_t data_id = buffer[6];
						uint8_t data_size = buffer[9]; // only 1byte or 4bytes values
						switch (cmd_type) {
							case 0x07: {
								switch (data_id) {
									// Motor reversing state
									case 0x67: {
										id(cover_reversed) = !!buffer[10];
										break;
									}
									// Operation mode state
									case 0x66: {
										switch (buffer[10]) {
											case 0x00:
												current_operation = COVER_OPERATION_CLOSING;
												break;
											case 0x02:
												current_operation = COVER_OPERATION_IDLE;
												break;
											case 0x01:
												current_operation = COVER_OPERATION_OPENING;
												break;
										}
										break;
									}
									// Position report during operation
									// Max value is 0x64 so the last byte is good enough
									case 0x68: {
										position = buffer[13] / 100.0f;
										id(cover_open) = !!position;
										break;
									}
									// Position report after operation
									case 0x65: {
										position = 1 - (buffer[13] / 100.0f);
										if (position > 0.95) position = 1;
										if (position < 0.05) position = 0;
										id(cover_open) = !!position;
										current_operation = COVER_OPERATION_IDLE;
										break;
									}
								}
								publish_state();
								break;
							}
						}
					}
					offset = 0;
				}
			}
		}
	}

	uint8_t crc;

	void writeByte(uint8_t data) {
		Serial.write(data);
		crc += data;
	}

	void writeHex(std::string data) {
		int i = 0;
		while (i < data.length()) {
			const char hex[2] = {data[i++], data[i++]};
			uint8_t d = strtoul(hex, NULL, 16);
			writeByte(d);
		}
	}

protected:
	uint16_t offset = 0;
	uint8_t buffer[1024];
};

class CustomAPI : public Component, public CustomAPIDevice {
public:
	void setup() override {
		register_service(&CustomAPI::setMotorNormal, "set_motor_normal");
		register_service(&CustomAPI::setMotorReversed, "set_motor_reversed");
		register_service(&CustomAPI::sendMessage, "send_command", {"data"});
	}


	void setMotorNormal() {
		sendMessage(TUYA_DISABLE_REVERSING);
	}

	void setMotorReversed() {
		sendMessage(TUYA_ENABLE_REVERSING);
	}

	void sendMessage(std::string data) {
		int i = 0;
		uint8_t sum = 0;
		while (i < data.length()) {
			const char hex[2] = {data[i++], data[i++]};
			uint8_t d = strtoul(hex, NULL, 16);
			sum += d;
			writeByte(d);
		}
		writeByte(sum);
	}

	void writeByte(uint8_t data) {
		Serial.write(data);
	}
};
```

**Comment by robertklep** [comment]
@brinzlee can you also post the (sanitized/minimal) YAML that you use with this component? So I can try and compile it myself to see what happens.

**Comment by brinzlee** [comment]
@robertklep Thank you again


```
substitutions:
  curtain_name: zemismart-curtain

esphome:
  name: zemismart-curtain
  comment: Zemismart Curtain Controller
#  platform: ESP8266
#  board: esp01_1m
  includes:
    - curtain.h

esp8266:
  board: esp01_1m

wifi:
  ssid: "**********"
  password: "*********"
#  use_address: zemismart_curtain.local


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "zemismart-curtain-hotspot"
    password: "*****************"
#    password: "*************"

captive_portal:

# Enable Home Assistant API
api:
  encryption:
    key: *******************************
#  password: "*******"

ota:
  platform: esphome
  password: "******"

# Disable logging
logger:
  # important because we are using uart0
  # to communicate with Tuya MCU
  baud_rate: 0

web_server:
  port: 80
  auth:
    username: ******
    password: !secret web_server_password

uart:
  - id: com_1
    tx_pin: GPIO015
    rx_pin: GPIO013
    baud_rate: 9600

globals:
  - id: cover_open
    type: bool
    restore_value: yes
    initial_value: "false"
  - id: cover_reversed
    type: bool
    restore_value: yes
    initial_value: "false"
  - id: cover_position
    type: float
    restore_value: yes
    initial_value: "0"

cover:
  - platform: custom
    lambda: |-
      auto curtain = new CustomCurtain();
      App.register_component(curtain);
      return {curtain};
    covers:
#      - name: Curtain
      - name: Drapes
        device_class: blind

custom_component:
  - lambda: |-
      return { new CustomAPI() };

sensor: 
# uptime value
  - platform: uptime
    name: ${curtain_name}_Uptime

# wifi strength
  - platform: wifi_signal
    name: ${curtain_name}_Wi-Fi_Signal
    update_interval: 180s

# firmware version
text_sensor:
  - platform: version
    name: ${curtain_name}_firmware_version
    
binary_sensor:
  - platform: status
    name: "Online"

external_components:
  - source:
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]
```

**Comment by robertklep** [comment]
@brinzlee I applied the suggested fix [posted here](https://github.com/esphome/esphome/issues/9616#issuecomment-3084456057) and it compiles now with v2025.7.2 😊

TL;DR:
```
api:
  custom_services: true
  encryption:
    key: '*******************************'
#  password: "*******"
```
